---
title: "Onderzoek naar de correlatie tussen hartslag en muziek"
output:
  html_document:
    css: style.css
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
author: 'Bram(456146)'
date: '9/5/2023'
---

## Meetmomenten
 * 11-5 eerste meetmoment in het lokaal
 * 12-5 eerste meetmoment buiten het lokaal
 * 15-5 tweede meetmoment buiten het lokaal
 * 2-6 derde meetmoment buiten het lokaal, metingen gedaan door Mathijs en Bram

## Uitleg
bpm_diff is het hartslag verschil; (bpm_na - bpm_voor)
```{r, echo = FALSE}
library(ggplot2)

file <- read.csv(
  "/homes/blkoobs/Documents/Kwartaal_4/R-Code/Bloeddruk_en_muziek/data.csv")

print(paste0("gemiddelde leeftijd = ",
mean(file$leeftijd)))
print(paste0("gemiddelde bpm verschil = ",
mean(file$bpm_diff)))
print(paste0("gemiddelde boven bloeddruk verschil = ",
mean(file$boven_bloeddruk_diff)))
print(paste0("gemiddelde onder bloeddruk verschil = ",
mean(file$onder_bloeddruk_diff)))
```


```{r visualize 1, echo = FALSE}
library(ggplot2)

file <- read.csv(
  "/homes/blkoobs/Documents/Kwartaal_4/R-Code/Bloeddruk_en_muziek/data.csv")

ggplot(data = file, mapping = aes(x = sexe, y = bpm_diff, color = vragenlijst, size = leeftijd)) +
geom_point(alpha = 0.8)
```
```{r visualize, echo = FALSE}
library(ggplot2)

file <- read.csv("/homes/blkoobs/Documents/Kwartaal_4/R-Code/Bloeddruk_en_muziek/data.csv")

ggplot(data = file, mapping = aes(x = sexe, y = bpm_diff)) +
geom_boxplot()
```

